# You must change these to your own details.
[package]
name = "game-of-life-wasm"
version = "0.1.0"
authors = ["Gaël Reyrol <me@gaelreyrol.dev>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false